# Custom Language File for Launcher Customizer

[ejs.app]
title = "Miray Tech"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "ДОБРО ПОЖАЛОВАТЬ В WESTEROSCRAFT"
welcomeDescription = "Наша миссия — воссоздать вселенную, придуманную автором Джорджем Р. Р. Мартином в его фэнтезийной серии «Песнь Льда и Огня». Благодаря совместным усилиям тысяч участников сообщества мы стремились создать Вестерос как можно более точно и достоверно в рамках Minecraft. Созданный нами мир ждёт, когда его исследуют. Совершите путешествие от Дорна до Стены, и, если вы не боитесь, — даже за её пределы, но лучше не медлить. Как зловеще предупреждают слова дома Старков: «Зима близко»."
welcomeDescCTA = "Вас отделяет всего несколько кликов от Вестероса."
